"""Generates docs/data/data_dictionary.md from the code that enforces it."""

from pathlib import Path

from opspulse.etl import config
from opspulse.etl.schema import DERIVED, GRAIN, KEYS, STAGING
from opspulse.etl.validate import CATALOGUE

DICTIONARY_PATH = config.PROJECT_ROOT / "docs" / "data" / "data_dictionary.md"


def render() -> str:
    window_start, window_end = (bound.date() for bound in config.ANALYSIS_WINDOW)
    lines = [
        "# Data dictionary",
        "",
        "Generated by `opspulse-etl dictionary` from `src/opspulse/etl/schema.py`, "
        "`validate.py` and `config.py`. Do not edit by hand; change the code and regenerate.",
        "",
        "Source: Olist Brazilian E-Commerce Public Dataset (Kaggle, CC BY-NC-SA 4.0).",
        "Timestamps are naive local times (America/Sao_Paulo). Money is BRL.",
        "",
        "## Business rules",
        "",
        f"- **Analysis window:** {window_start} to {window_end}. The months outside it hold "
        "a few hundred orders between them, so trends and recency use this window.",
        "- **Sales** exclude orders with status "
        + ", ".join(f"`{status}`" for status in sorted(config.NON_SALE_STATUSES))
        + ".",
        f"- **Payment reconciliation:** |payment_total − order_total| ≤ "
        f"R${config.RECONCILIATION_MATCH_TOLERANCE:.2f} is MATCHED, "
        f"≤ R${config.RECONCILIATION_MINOR_TOLERANCE:.2f} is MINOR_DIFFERENCE, otherwise "
        "SIGNIFICANT_DIFFERENCE. Orders without items or payments get their own status. "
        "Differences are not assumed to be fraud: installment interest and vouchers cause many.",
        f"- **Geolocation:** points outside latitude {config.BRAZIL_LATITUDE} / longitude "
        f"{config.BRAZIL_LONGITUDE} are excluded from zip centroids. A centroid is an area, "
        "never an address.",
        f"- **Run failure:** any CRITICAL issue, or any table losing more than "
        f"{config.CATASTROPHIC_REJECTION_SHARE:.0%} of its rows to rejection.",
        "- **Severity:** CRITICAL fails the run · ERROR rejects the row · WARNING keeps the row "
        "and records the issue.",
        "",
        "## Staging tables",
    ]
    for table, columns in STAGING.items():
        key = KEYS[table]
        lines += [
            "",
            f"### {table}",
            "",
            f"Source `{config.SOURCE_FILES[table]}` · grain: {GRAIN[table]} · key: "
            + (", ".join(f"`{column}`" for column in key) if key else "none"),
            "",
            "| column | source column | type | required | meaning |",
            "|---|---|---|---|---|",
        ]
        for name, column in columns.items():
            lines.append(
                f"| `{name}` | `{column.source}` | {column.kind} "
                f"| {'yes' if column.required else ''} | {column.description} |"
            )

    lines += [
        "",
        "## Derived fields (lineage)",
        "",
        "| dataset | field | from | category | definition |",
        "|---|---|---|---|---|",
    ]
    for derived in DERIVED:
        lines.append(
            f"| {derived.table} | `{derived.field}` | {derived.sources} | {derived.category} "
            f"| {derived.definition} |"
        )

    lines += [
        "",
        "## Validation rules",
        "",
        "| table | code | severity | gate | meaning |",
        "|---|---|---|---|---|",
    ]
    for (table, code), entry in CATALOGUE.items():
        lines.append(
            f"| {table} | `{code}` | {entry.severity} | {entry.gate} | {entry.description} |"
        )
    return "\n".join(lines) + "\n"


def write_dictionary(path: Path = DICTIONARY_PATH) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(), encoding="utf-8", newline="\n")
    return path
