"""The run's quality report: written after every run, including failed ones."""

import json
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd

from opspulse.etl import config
from opspulse.etl.validate import CATALOGUE, CRITICAL, WARNING

RULE_GATES = ["keys", "completeness", "values", "dates", "references"]


@dataclass
class RunState:
    """Facts collected while the pipeline runs; whatever exists when it stops is reported."""

    run_id: str
    started_at: str
    manifest: dict | None = None
    source_rows: dict[str, int] = field(default_factory=dict)
    issues: pd.DataFrame | None = None
    accepted_rows: dict[str, int] = field(default_factory=dict)
    rejected_rows: dict[str, int] = field(default_factory=dict)
    outputs: dict[str, dict[str, int]] = field(default_factory=dict)
    gates: dict[str, str] = field(default_factory=dict)
    problems: list[str] = field(default_factory=list)


def _rule_gates(issues: pd.DataFrame | None) -> dict[str, str]:
    if issues is None:
        return dict.fromkeys(RULE_GATES, "NOT_RUN")
    gate_of_issue = pd.Series(
        [CATALOGUE[key].gate for key in zip(issues["table"], issues["code"], strict=True)],
        index=issues.index,
        dtype="str",
    )
    gates = {}
    for gate in RULE_GATES:
        hits = issues[gate_of_issue == gate]
        if (hits["severity"] == CRITICAL).any():
            gates[gate] = "FAIL"
        elif not hits.empty:
            gates[gate] = "WARN"
        else:
            gates[gate] = "PASS"
    return gates


def build_report(state: RunState, duration_seconds: float) -> dict:
    issues = state.issues
    warning_count = 0 if issues is None else int((issues["severity"] == WARNING).sum())
    if state.problems:
        status = "FAILED"
    elif warning_count:
        status = "SUCCESS_WITH_WARNINGS"
    else:
        status = "SUCCESS"

    tables = {}
    for table, source_rows in state.source_rows.items():
        entry = {
            "source_rows": source_rows,
            "accepted_rows": state.accepted_rows.get(table),
            "rejected_rows": state.rejected_rows.get(table),
        }
        if issues is not None:
            table_issues = issues[issues["table"] == table]
            entry["issue_counts"] = table_issues["code"].value_counts().sort_index().to_dict()
        tables[table] = entry

    issue_summary = []
    if issues is not None and not issues.empty:
        grouped = (
            issues.groupby(["table", "code", "severity", "stage"]).size().reset_index(name="rows")
        )
        for row in grouped.itertuples(index=False):
            issue_summary.append(
                {
                    "table": row.table,
                    "code": row.code,
                    "severity": row.severity,
                    "stage": row.stage,
                    "rows": int(row.rows),
                    "description": CATALOGUE[(row.table, row.code)].description,
                }
            )

    return {
        "run_id": state.run_id,
        "status": status,
        "started_at": state.started_at,
        "duration_seconds": round(duration_seconds, 1),
        "analysis_window": [str(bound) for bound in config.ANALYSIS_WINDOW],
        "quality_gates": state.gates | _rule_gates(issues),
        "critical_problems": state.problems,
        "totals": {
            "source_rows": sum(state.source_rows.values()),
            "accepted_rows": sum(state.accepted_rows.values()),
            "rejected_rows": sum(state.rejected_rows.values()),
            "warnings": warning_count,
        },
        "tables": tables,
        "issues": issue_summary,
        "outputs": state.outputs,
        "sources": (state.manifest or {}).get("files", {}),
    }


def _value(value) -> str:
    return "—" if value is None else f"{value:,}"


def render_markdown(report: dict) -> str:
    lines = [
        "# Data quality report",
        "",
        f"**{report['status']}** · run `{report['run_id']}` · started {report['started_at']} · "
        f"{report['duration_seconds']}s. Generated by `opspulse-etl run`; do not edit by hand.",
        "",
    ]
    if report["critical_problems"]:
        lines += ["## Critical problems", ""]
        lines += [f"- {problem}" for problem in report["critical_problems"]]
        lines.append("")

    lines += ["## Quality gates", "", "| gate | status |", "|---|---|"]
    lines += [f"| {gate} | {status} |" for gate, status in report["quality_gates"].items()]

    lines += [
        "",
        "## Tables",
        "",
        "| table | source rows | accepted | rejected |",
        "|---|---:|---:|---:|",
    ]
    for table, entry in report["tables"].items():
        lines.append(
            f"| {table} | {_value(entry['source_rows'])} | {_value(entry['accepted_rows'])} "
            f"| {_value(entry['rejected_rows'])} |"
        )

    if report["issues"]:
        lines += [
            "",
            "## Issues",
            "",
            "ERROR and CRITICAL rows are rejected; WARNING rows are kept and listed in "
            "`data/processed/quality/warnings.parquet`.",
            "",
            "| table | code | severity | rows | meaning |",
            "|---|---|---|---:|---|",
        ]
        for issue in report["issues"]:
            lines.append(
                f"| {issue['table']} | `{issue['code']}` | {issue['severity']} "
                f"| {issue['rows']:,} | {issue['description']} |"
            )

    if report["outputs"]:
        lines += ["", "## Outputs", "", "| layer | dataset | rows |", "|---|---|---:|"]
        for layer, datasets in report["outputs"].items():
            for name, rows in datasets.items():
                lines.append(f"| {layer} | {name} | {rows:,} |")
    return "\n".join(lines) + "\n"


def write_report(report: dict, report_dir: Path) -> None:
    (report_dir / "runs").mkdir(parents=True, exist_ok=True)
    payload = json.dumps(report, indent=2, ensure_ascii=False, allow_nan=False)
    outputs = {
        report_dir / "runs" / f"{report['run_id']}.json": payload,
        report_dir / "latest_report.json": payload,
        report_dir / "latest_report.md": render_markdown(report),
    }
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8", newline="\n")
